name: cryto_wallet_3
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  iconsax_flutter: ^1.0.0
  animate_do: ^2.0.0
  flutter_advanced_drawer: ^1.2.3+1
  flutter_svg_icons: ^0.0.1+4
  flutter_svg: ^2.0.10+1
  flutter_animate: ^4.5.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:

  uses-material-design: true

  assets:
    - assets\images\avatar.jpg
  fonts:
    - family: jbm
      fonts:
        - asset: fonts/JetBrainsMonoNerdFont-Bold.ttf
          weight: 700  # 700 correspond à FontWeight.bold
        - asset: fonts/JetBrainsMonoNerdFontMono-MediumItalic.ttf
          weight: 500  # 500 correspond à FontWeight.w500 (medium)
          style: italic
        - asset: fonts/JetBrainsMonoNerdFontMono-Thin.ttf
          weight: 100  # 100 correspond à FontWeight.w100 (thin)
        - asset: fonts/JetBrainsMonoNerdFontMono-Light.ttf
          weight: 300  # 300 correspond à FontWeight.w300 (light)
        - asset: fonts/JetBrainsMonoNerdFontMono-ExtraBoldItalic.ttf
          weight: 800  # 800 correspond à FontWeight.w800 (extra bold)
          style: italic
        - asset: fonts/JetBrainsMonoNerdFont-ExtraLight.ttf
          weight: 200  # 200 correspond à FontWeight.w200 (extra light)
        - asset: fonts/JetBrainsMonoNerdFont-Medium.ttf
          weight: 500  # 500 correspond à FontWeight.w500 (medium)

